// func/data.js
export const products = [
  {
    id: 1,
    name: "Blazer Casual Elegante",
    category: "social",
    price: 79.99,
    oldPrice: 99.99,
    image: "/vintcy-store/assets/img/blazer_casual_elegante.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 42,
    tab: "sale",
  },
  {
    id: 2,
    name: "Camiseta Básica Regular",
    category: "casual",
    price: 89.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/camiseta_basica (1).jpg",
    badge: "New",
    rating: 4.8,
    reviews: 28,
    tab: "new",
  },
  {
    id: 3,
    name: "Blazer Esporte Fino Texturizado",
    category: "social",
    price: 119.99,
    oldPrice: 149.99,
    image: "/vintcy-store/assets/img/blazer_esporte_fino_texturizado.jpg",
    badge: "Sale",
    rating: 4.2,
    reviews: 15,
    tab: "sale",
  },
  {
    id: 4,
    name: "Camiseta Gráfica Casual Geo",
    category: "casual",
    price: 229.99,
    oldPrice: 269.99,
    image: "/vintcy-store/assets/img/camiseta_grafica_casual_geo.jpg",
    badge: "Hot",
    rating: 4.6,
    reviews: 31,
    tab: "best",
  },
  {
    id: 5,
    name: "Camiseta Listrada Casual Náutica",
    category: "casual",
    price: 149.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/camiseta_listrada_casual_nautica.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 54,
    tab: "new",
  },
  {
    id: 6,
    name: "Camiseta Minimalista Vintcy",
    category: "casual",
    price: 129.99,
    oldPrice: 159.99,
    image: "/vintcy-store/assets/img/camiseta_minimalista_vintcy.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 22,
    tab: "sale",
  },
  {
    id: 7,
    name: "Camiseta Regular Fit",
    category: "casual",
    price: 99.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/camiseta_regular_fit.jpg",
    badge: null,
    rating: 4.3,
    reviews: 19,
    tab: "best",
  },
  {
    id: 8,
    name: "Camiseta Slim Fit",
    category: "casual",
    price: 199.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/camiseta_slim_fit.jpg",
    badge: "New",
    rating: 4.9,
    reviews: 22,
    tab: "new",
  },

  {
    id: 9,
    name: "Polo Casual Detalhe Slim",
    category: "polos",
    price: 59.99,
    oldPrice: 79.99,
    image: "/vintcy-store/assets/img/polo_casual_detalhe_slim.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 27,
    tab: "sale",
  },
  {
    id: 10,
    name: "Polo Essencial de Malha",
    category: "polos",
    price: 79.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/polo_essencial_de_malha.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 15,
    tab: "new",
  },
  {
    id: 11,
    name: "Polo Textura Listrada Comfort",
    category: "polos",
    price: 89.99,
    oldPrice: 119.99,
    image: "/vintcy-store/assets/img/polo_textura_listrada_comfort.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 33,
    tab: "sale",
  },
  {
    id: 12,
    name: "Terno Alfaiate Completo",
    category: "social",
    price: 69.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/terno_alfaiate_completo.jpg",
    badge: null,
    rating: 4.3,
    reviews: 41,
    tab: "best",
  },
  {
    id: 13,
    name: "Terno Costume de Duas Peças",
    category: "social",
    price: 49.99,
    oldPrice: 64.99,
    image: "/vintcy-store/assets/img/terno_costume_de_duas_peças.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 58,
    tab: "sale",
  },
  {
    id: 14,
    name: "Blazer Esporte Fino Lapela Slim",
    category: "social",
    price: 99.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Blazer_Esporte_Fino_Lapela_Slim.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 19,
    tab: "new",
  },
  {
    id: 15,
    name: "Calça de Alfaiataria Slim Fit",
    category: "calças",
    price: 44.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Calça_de_Alfaiataria_Slim_Fit.jpg",
    badge: null,
    rating: 4.2,
    reviews: 24,
    tab: "best",
  },
  {
    id: 16,
    name: "Calça de Alfaiataria Xadrez Príncipe de Gales",
    category: "calças",
    price: 54.99,
    oldPrice: 69.99,
    image:
      "/vintcy-store/assets/img/Calça_de_Alfaiataria_Xadrez_Príncipe_de_Gales.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 31,
    tab: "sale",
  },
  {
    id: 17,
    name: "Calça de Lã Clássica",
    category: "calças",
    price: 199.99,
    oldPrice: 249.99,
    image: "/vintcy-store/assets/img/Calça_de_Lã_Clássica.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 22,
    tab: "sale",
  },
  {
    id: 18,
    name: "Camisa Slim fit",
    category: "social",
    price: 39.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Camisa_Slim_fit.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 13,
    tab: "new",
  },
  {
    id: 19,
    name: "Camisa Social Básica",
    category: "social",
    price: 34.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Camisa_Social_Básica.jpg",
    badge: null,
    rating: 4.6,
    reviews: 67,
    tab: "best",
  },
  {
    id: 20,
    name: "Jaqueta Casual de Sarja",
    category: "jaquetas",
    price: 64.99,
    oldPrice: 79.99,
    image: "/vintcy-store/assets/img/Jaqueta_Casual_de_Sarja.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 29,
    tab: "sale",
  },
  {
    id: 21,
    name: "Jaqueta Corta-Vento Casual",
    category: "jaquetas",
    price: 54.99,
    oldPrice: 74.99,
    image: "/vintcy-store/assets/img/Jaqueta_Corta-Vento_Casual.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 61,
    tab: "sale",
  },
  {
    id: 22,
    name: "Jaqueta Hoodie Casual",
    category: "jaquetas",
    price: 19.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Jaqueta_Hoodie_Casual.jpg",
    badge: null,
    rating: 4.1,
    reviews: 25,
    tab: "best",
  },
  {
    id: 23,
    name: "Moletom Básico com Capuz",
    category: "moletons",
    price: 89.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Moletom_Básico_com_Capuz.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 12,
    tab: "new",
  },
  {
    id: 24,
    name: "Moletom Careca Básico",
    category: "moletons",
    price: 149.99,
    oldPrice: 199.99,
    image: "/vintcy-store/assets/img/Moletom_Careca_Básico.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 38,
    tab: "sale",
  },
  {
    id: 25,
    name: "Moletom com Zíper e Capuz",
    category: "moletons",
    price: 94.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Moletom_com_Zíper_e_Capuz.jpg",
    badge: null,
    rating: 4.8,
    reviews: 44,
    tab: "best",
  },
  {
    id: 26,
    name: "Calça Jeans Reta",
    category: "calças",
    price: 34.99,
    oldPrice: 44.99,
    image: "/vintcy-store/assets/img/Calça_Jeans_Reta.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 51,
    tab: "sale",
  },
  {
    id: 27,
    name: "Calça Chino Casual",
    category: "calças",
    price: 29.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Calça_Chino_casual.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 19,
    tab: "new",
  },
  {
    id: 28,
    name: "Calça Jeans Slim Fit",
    category: "calças",
    price: 119.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Calça_Jeans_Slim_Fit.jpg",
    badge: null,
    rating: 4.5,
    reviews: 33,
    tab: "best",
  },
  {
    id: 29,
    name: "Calça Jogger de Sarja",
    category: "calças",
    price: 44.99,
    oldPrice: 59.99,
    image: "/vintcy-store/assets/img/Calça_Jogger_de_Sarja.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 82,
    tab: "sale",
  },
  {
    id: 30,
    name: "Calça Cargo Casual",
    category: "calças",
    price: 24.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Calça_Cargo_Casual.jpg",
    badge: "New",
    rating: 4.2,
    reviews: 14,
    tab: "new",
  },
  {
    id: 31,
    name: "Cinto Social de Couro Liso",
    category: "acessorios",
    price: 129.99,
    oldPrice: 169.99,
    image: "/vintcy-store/assets/img/Cinto_Social_de_Couro_Liso.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 27,
    tab: "sale",
  },
  {
    id: 32,
    name: "Cinto Social de Couro Clássico",
    category: "acessorios",
    price: 79.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Cinto_Social_de_Couro_Clássico.jpg",
    badge: null,
    rating: 4.0,
    reviews: 18,
    tab: "best",
  },
  {
    id: 33,
    name: "Cinto Social de Couro Texturizado",
    category: "acessorios",
    price: 17.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Cinto_Social_de_Couro_Texturizado.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 9,
    tab: "new",
  },
  {
    id: 34,
    name: "Gravata Social Lisa de Seda",
    category: "acessorios",
    price: 34.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Gravata_Social_Lisa_de_Seda.jpg",
    badge: null,
    rating: 4.4,
    reviews: 29,
    tab: "best",
  },
  {
    id: 35,
    name: "Gravata Social com Padrão Listrado",
    category: "acessorios",
    price: 99.99,
    oldPrice: 129.99,
    image: "/vintcy-store/assets/img/Gravata_Social_com_Padrão_Listrado.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 55,
    tab: "sale",
  },
  {
    id: 36,
    name: "Gravata Social de Poá",
    category: "acessorios",
    price: 79.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Gravata_Social_de_Poá.jpg",
    badge: "New",
    rating: 4.9,
    reviews: 22,
    tab: "new",
  },
  {
    id: 37,
    name: "Meias Sociais Clássicas",
    category: "acessorios",
    price: 39.99,
    oldPrice: 49.99,
    image: "/vintcy-store/assets/img/Meias_Sociais_Clássicas.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 71,
    tab: "sale",
  },
  {
    id: 38,
    name: "Abotoaduras Clássicas",
    category: "acessorios",
    price: 39.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Abotoaduras_Clássicas.jpg",
    badge: null,
    rating: 4.3,
    reviews: 31,
    tab: "best",
  },
  {
    id: 39,
    name: "Relógio Casual Cronógrafo",
    category: "acessorios",
    price: 59.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Relógio_Casual_Cronógrafo.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 40,
    name: "Relógio Casual Minimalista",
    category: "acessorios",
    price: 44.99,
    oldPrice: 54.99,
    image: "/vintcy-store/assets/img/Relógio_Casual_Minimalista.jpg",
    badge: "Sale",
    rating: 4.2,
    reviews: 23,
    tab: "sale",
  },
  {
    id: 41,
    name: "Relógio Casual de Couro Marrom",
    category: "acessorios",
    price: 49.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Relógio_Casual_de_Couro_Marrom.jpg",
    badge: null,
    rating: 4.5,
    reviews: 48,
    tab: "best",
  },
  {
    id: 42,
    name: "Óculos de Sol Casual Clássico",
    category: "acessorios",
    price: 34.99,
    oldPrice: 44.99,
    image: "/vintcy-store/assets/img/Óculos_de_Sol_Casual_Clássico.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 11,
    tab: "sale",
  },
  {
    id: 43,
    name: "Óculos de Sol Masculino Aviador",
    category: "acessorios",
    price: 69.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Óculos_de_Sol_Masculino_Aviador.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 26,
    tab: "new",
  },
  {
    id: 44,
    name: "Óculos de Sol Masculino Clubmaster",
    category: "acessorios",
    price: 74.99,
    oldPrice: 89.99,
    image: "/vintcy-store/assets/img/Óculos_de_Sol_Masculino_Clubmaster.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 63,
    tab: "sale",
  },
  {
    id: 45,
    name: "Óculos de Sol Casual Geométrico",
    category: "acessorios",
    price: 59.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Óculos_de_Sol_Casual_Geométrico.jpg",
    badge: null,
    rating: 4.1,
    reviews: 19,
    tab: "best",
  },
  {
    id: 46,
    name: "Bermuda Cargo",
    category: "bermudas",
    price: 64.99,
    oldPrice: 79.99,
    image: "/vintcy-store/assets/img/Bermuda_Cargo.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 37,
    tab: "sale",
  },
  {
    id: 47,
    name: "Bermuda Chino",
    category: "bermudas",
    price: 54.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Bermuda_Chino.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 21,
    tab: "new",
  },
  {
    id: 48,
    name: "Bermuda de Alfaiataria",
    category: "bermudas",
    price: 69.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Bermuda_de_alfaiataria.jpg",
    badge: null,
    rating: 4.0,
    reviews: 15,
    tab: "best",
  },
  {
    id: 49,
    name: "Bermuda de Moletom",
    category: "bermudas",
    price: 29.99,
    oldPrice: 39.99,
    image: "/vintcy-store/assets/img/Bermuda_de_moletom.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 8,
    tab: "sale",
  },
  {
    id: 50,
    name: "Sapato Oxford Cap-Toe",
    category: "sapatos",
    price: 109.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Sapato_Oxford_Cap-Toe.jpg",
    badge: null,
    rating: 4.7,
    reviews: 41,
    tab: "best",
  },
  {
    id: 51,
    name: "Sapato Monk Strap Duplo Preto",
    category: "sapatos",
    price: 34.99,
    oldPrice: 44.99,
    image: "/vintcy-store/assets/img/Sapato_Monk_Strap_Duplo_Preto.jpg",
    badge: "Sale",
    rating: 4.2,
    reviews: 93,
    tab: "sale",
  },
  {
    id: 52,
    name: "Bota Chelsea",
    category: "botas",
    price: 44.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Bota_Chelsea.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 30,
    tab: "new",
  },
  {
    id: 53,
    name: "Bota Brogue",
    category: "botas",
    price: 119.99,
    oldPrice: 149.99,
    image: "/vintcy-store/assets/img/Bota_Brogue.jpg",
    badge: "Sale",
    rating: 4.8,
    reviews: 28,
    tab: "sale",
  },
  {
    id: 54,
    name: "Tênis Casual de Couro Liso",
    category: "tenis",
    price: 94.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Tênis_Casual_de_Couro_Liso.jpg",
    badge: null,
    rating: 4.4,
    reviews: 22,
    tab: "best",
  },
  {
    id: 55,
    name: "Tênis de Couro Com Detalhes de Camurça",
    category: "tenis",
    price: 24.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Tênis_de_Couro_com_Detalhes_de_Camurça.jpg",
    badge: "New",
    rating: 4.9,
    reviews: 7,
    tab: "new",
  },
  {
    id: 56,
    name: "Mocassim Penny de Couro Marrom",
    category: "mocassins",
    price: 84.99,
    oldPrice: 109.99,
    image: "/vintcy-store/assets/img/Mocassim_Penny_de_Couro_Marrom.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 19,
    tab: "sale",
  },
  {
    id: 57,
    name: "Mocassim Driver de Camurça",
    category: "mocassins",
    price: 39.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Mocassim_Driver_de_Camurça.jpg",
    badge: null,
    rating: 4.3,
    reviews: 52,
    tab: "best",
  },
  {
    id: 58,
    name: "Mochila de Couro Minimalista",
    category: "mochilas",
    price: 49.99,
    oldPrice: 64.99,
    image: "/vintcy-store/assets/img/Mochila_de_Couro_Minimalista.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 44,
    tab: "sale",
  },
  {
    id: 59,
    name: "Mochila de Couro Roll-Top",
    category: "mochilas",
    price: 14.99,
    oldPrice: null,
    image: "/vintcy-store/assets/img/Mochila_de_Couro_Roll-Top.jpg",
    badge: null,
    rating: 4.0,
    reviews: 67,
    tab: "best",
  },
  {
    id: 60,
    name: "Mochila Esportiva Minimalista",
    category: "mochilas",
    price: 179.99,
    oldPrice: 229.99,
    image: "/vintcy-store/assets/img/Mochila_esportiva_minimalista.jpg",
    badge: "Sale",
    rating: 4.9,
    reviews: 35,
    tab: "sale",
  },
];
