// func/data.js
export const products = [
  {
    id: 1,
    name: "Camiseta Casual Premium",
    category: "casual",
    price: 79.99,
    oldPrice: 99.99,
    image: "https://picsum.photos/seed/casual1/300/300.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 42,
    tab: "sale",
  },
  {
    id: 2,
    name: "Polo Clássica Masculina",
    category: "polos",
    price: 89.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/polo1/300/300.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 28,
    tab: "new",
  },
  {
    id: 3,
    name: "Camisa Social Slim Fit",
    category: "social",
    price: 119.99,
    oldPrice: 149.99,
    image: "https://picsum.photos/seed/social1/300/300.jpg",
    badge: "Sale",
    rating: 4.2,
    reviews: 15,
    tab: "sale",
  },
  {
    id: 4,
    name: "Jaqueta Jeans Forrada",
    category: "jaquetas",
    price: 229.99,
    oldPrice: 269.99,
    image: "https://picsum.photos/seed/jaqueta1/300/300.jpg",
    badge: "Hot",
    rating: 4.6,
    reviews: 31,
    tab: "best",
  },
  {
    id: 5,
    name: "Moletom Oversized Básico",
    category: "moletons",
    price: 149.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/moletom1/300/300.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 54,
    tab: "new",
  },
  {
    id: 6,
    name: "Calça Jeans Skinny",
    category: "calças",
    price: 129.99,
    oldPrice: 159.99,
    image: "https://picsum.photos/seed/calca1/300/300.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 22,
    tab: "sale",
  },
  {
    id: 7,
    name: "Bermuda Sarja Casual",
    category: "bermudas",
    price: 99.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/bermuda1/300/300.jpg",
    badge: null,
    rating: 4.3,
    reviews: 19,
    tab: "best",
  },
  {
    id: 8,
    name: "Relógio Minimalista Couro",
    category: "acessorios",
    price: 199.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/acessorio1/300/300.jpg",
    badge: "New",
    rating: 4.9,
    reviews: 22,
    tab: "new",
  },

  {
    id: 9,
    name: "Classic Oxford Shirt",
    category: "Men's Wear",
    price: 59.99,
    oldPrice: 79.99,
    image: "https://picsum.photos/seed/oxfordshirt/300/300.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 27,
    tab: "sale",
  },
  {
    id: 10,
    name: "Summer Floral Dress",
    category: "Women's Wear",
    price: 79.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/floraldress/300/300.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 15,
    tab: "new",
  },
  {
    id: 11,
    name: "Wool Blend Sweater",
    category: "Men's Wear",
    price: 89.99,
    oldPrice: 119.99,
    image: "https://picsum.photos/seed/sweater/300/300.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 33,
    tab: "sale",
  },
  {
    id: 12,
    name: "High-Waist Skinny Jeans",
    category: "Women's Wear",
    price: 69.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/skinnyjeans/300/300.jpg",
    badge: null,
    rating: 4.3,
    reviews: 41,
    tab: "best",
  },
  {
    id: 13,
    name: "Canvas Sneakers",
    category: "Footwear",
    price: 49.99,
    oldPrice: 64.99,
    image: "https://picsum.photos/seed/sneakers/300/300.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 58,
    tab: "sale",
  },
  {
    id: 14,
    name: "Leather Crossbody Bag",
    category: "Accessories",
    price: 99.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/crossbodybag/300/300.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 19,
    tab: "new",
  },
  {
    id: 15,
    name: "Striped Polo Shirt",
    category: "Men's Wear",
    price: 44.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/poloshirt/300/300.jpg",
    badge: null,
    rating: 4.2,
    reviews: 24,
    tab: "best",
  },
  {
    id: 16,
    name: "Pleated Midi Skirt",
    category: "Women's Wear",
    price: 54.99,
    oldPrice: 69.99,
    image: "https://picsum.photos/seed/midiskirt/300/300.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 31,
    tab: "sale",
  },
  {
    id: 17,
    name: "Wool Winter Coat",
    category: "Outerwear",
    price: 199.99,
    oldPrice: 249.99,
    image: "https://picsum.photos/seed/wintercoat/300/300.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 22,
    tab: "sale",
  },
  {
    id: 18,
    name: "Silk Scarf Collection",
    category: "Accessories",
    price: 39.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/silkscarf/300/300.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 13,
    tab: "new",
  },
  {
    id: 19,
    name: "Athletic Leggings",
    category: "Activewear",
    price: 34.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/leggings/300/300.jpg",
    badge: null,
    rating: 4.6,
    reviews: 67,
    tab: "best",
  },
  {
    id: 20,
    name: "Casual Chino Pants",
    category: "Men's Wear",
    price: 64.99,
    oldPrice: 79.99,
    image: "https://picsum.photos/seed/chinos/300/300.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 29,
    tab: "sale",
  },
  {
    id: 21,
    name: "Graphic Print Hoodie",
    category: "Men's Wear",
    price: 54.99,
    oldPrice: 74.99,
    image: "https://picsum.photos/seed/graphichoodie/300/300.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 61,
    tab: "sale",
  },
  {
    id: 22,
    name: "Ribbed Knit Beanie",
    category: "Accessories",
    price: 19.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/beanie/300/300.jpg",
    badge: null,
    rating: 4.1,
    reviews: 25,
    tab: "best",
  },
  {
    id: 23,
    name: "Ankle Strap Heels",
    category: "Footwear",
    price: 89.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/heels/300/300.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 12,
    tab: "new",
  },
  {
    id: 24,
    name: "Quilted Puffer Jacket",
    category: "Outerwear",
    price: 149.99,
    oldPrice: 199.99,
    image: "https://picsum.photos/seed/pufferjacket/300/300.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 38,
    tab: "sale",
  },
  {
    id: 25,
    name: "Bohemian Maxi Dress",
    category: "Women's Wear",
    price: 94.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/maxidress/300/300.jpg",
    badge: null,
    rating: 4.8,
    reviews: 44,
    tab: "best",
  },
  {
    id: 26,
    name: "Classic Aviator Sunglasses",
    category: "Accessories",
    price: 34.99,
    oldPrice: 44.99,
    image: "https://picsum.photos/seed/aviators/300/300.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 51,
    tab: "sale",
  },
  {
    id: 27,
    name: "Performance Running Shorts",
    category: "Activewear",
    price: 29.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/runningshorts/300/300.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 19,
    tab: "new",
  },
  {
    id: 28,
    name: "Slim-Fit Blazer",
    category: "Men's Wear",
    price: 119.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/blazer/300/300.jpg",
    badge: null,
    rating: 4.5,
    reviews: 33,
    tab: "best",
  },
  {
    id: 29,
    name: "Fleece-Lined Leggings",
    category: "Women's Wear",
    price: 44.99,
    oldPrice: 59.99,
    image: "https://picsum.photos/seed/fleeceleggings/300/300.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 82,
    tab: "sale",
  },
  {
    id: 30,
    name: "Canvas Tote Bag",
    category: "Accessories",
    price: 24.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/totebag/300/300.jpg",
    badge: "New",
    rating: 4.2,
    reviews: 14,
    tab: "new",
  },
  {
    id: 31,
    name: "Heavy-Duty Work Boots",
    category: "Footwear",
    price: 129.99,
    oldPrice: 169.99,
    image: "https://picsum.photos/seed/workboots/300/300.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 27,
    tab: "sale",
  },
  {
    id: 32,
    name: "Pinstripe Trousers",
    category: "Women's Wear",
    price: 79.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/pinstripepants/300/300.jpg",
    badge: null,
    rating: 4.0,
    reviews: 18,
    tab: "best",
  },
  {
    id: 33,
    name: "Kids' Graphic T-Shirt",
    category: "Kids' Wear",
    price: 17.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/kidstee/300/300.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 9,
    tab: "new",
  },
  {
    id: 34,
    name: "Satin Camisole Top",
    category: "Women's Wear",
    price: 34.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/camisole/300/300.jpg",
    badge: null,
    rating: 4.4,
    reviews: 29,
    tab: "best",
  },
  {
    id: 35,
    name: "Rugged Denim Jacket",
    category: "Outerwear",
    price: 99.99,
    oldPrice: 129.99,
    image: "https://picsum.photos/seed/denimjacket/300/300.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 55,
    tab: "sale",
  },
  {
    id: 36,
    name: "Minimalist Watch",
    category: "Accessories",
    price: 79.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/minimalistwatch/300/300.jpg",
    badge: "New",
    rating: 4.9,
    reviews: 22,
    tab: "new",
  },
  {
    id: 37,
    name: "Compression Sports Bra",
    category: "Activewear",
    price: 39.99,
    oldPrice: 49.99,
    image: "https://picsum.photos/seed/sportsbra/300/300.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 71,
    tab: "sale",
  },
  {
    id: 38,
    name: "Linen Blend Shorts",
    category: "Men's Wear",
    price: 39.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/linenshorts/300/300.jpg",
    badge: null,
    rating: 4.3,
    reviews: 31,
    tab: "best",
  },
  {
    id: 39,
    name: "Chunky Platform Sandals",
    category: "Footwear",
    price: 59.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/platformsandals/300/300.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 40,
    name: "Woven Leather Belt",
    category: "Accessories",
    price: 44.99,
    oldPrice: 54.99,
    image: "https://picsum.photos/seed/leatherbelt/300/300.jpg",
    badge: "Sale",
    rating: 4.2,
    reviews: 23,
    tab: "sale",
  },
  {
    id: 41,
    name: "Plaid Flannel Shirt",
    category: "Men's Wear",
    price: 49.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/flannelshirt/300/300.jpg",
    badge: null,
    rating: 4.5,
    reviews: 48,
    tab: "best",
  },
  {
    id: 42,
    name: "Kids' Denim Overalls",
    category: "Kids' Wear",
    price: 34.99,
    oldPrice: 44.99,
    image: "https://picsum.photos/seed/kidsoveralls/300/300.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 11,
    tab: "sale",
  },
  {
    id: 43,
    name: "Longline Cardigan",
    category: "Women's Wear",
    price: 69.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/cardigan/300/300.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 26,
    tab: "new",
  },
  {
    id: 44,
    name: "High-Top Sneakers",
    category: "Footwear",
    price: 74.99,
    oldPrice: 89.99,
    image: "https://picsum.photos/seed/hightops/300/300.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 63,
    tab: "sale",
  },
  {
    id: 45,
    name: "Polo Neck Sweater",
    category: "Women's Wear",
    price: 59.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/poloneck/300/300.jpg",
    badge: null,
    rating: 4.1,
    reviews: 19,
    tab: "best",
  },
  {
    id: 46,
    name: "Track Jacket",
    category: "Activewear",
    price: 64.99,
    oldPrice: 79.99,
    image: "https://picsum.photos/seed/trackjacket/300/300.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 37,
    tab: "sale",
  },
  {
    id: 47,
    name: "Bamboo Pajama Set",
    category: "Loungewear",
    price: 54.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/pajamas/300/300.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 21,
    tab: "new",
  },
  {
    id: 48,
    name: "Corduroy Pants",
    category: "Men's Wear",
    price: 69.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/corduroys/300/300.jpg",
    badge: null,
    rating: 4.0,
    reviews: 15,
    tab: "best",
  },
  {
    id: 49,
    name: "Wide-Brim Hat",
    category: "Accessories",
    price: 29.99,
    oldPrice: 39.99,
    image: "https://picsum.photos/seed/widebrimhat/300/300.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 8,
    tab: "sale",
  },
  {
    id: 50,
    name: "Waterproof Raincoat",
    category: "Outerwear",
    price: 109.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/raincoat/300/300.jpg",
    badge: null,
    rating: 4.7,
    reviews: 41,
    tab: "best",
  },
  {
    id: 51,
    name: "V-Neck T-Shirt Pack",
    category: "Men's Wear",
    price: 34.99,
    oldPrice: 44.99,
    image: "https://picsum.photos/seed/teepack/300/300.jpg",
    badge: "Sale",
    rating: 4.2,
    reviews: 93,
    tab: "sale",
  },
  {
    id: 52,
    name: "Midi Slip Skirt",
    category: "Women's Wear",
    price: 44.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/slipskirt/300/300.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 30,
    tab: "new",
  },
  {
    id: 53,
    name: "Leather Messenger Bag",
    category: "Accessories",
    price: 119.99,
    oldPrice: 149.99,
    image: "https://picsum.photos/seed/messengerbag/300/300.jpg",
    badge: "Sale",
    rating: 4.8,
    reviews: 28,
    tab: "sale",
  },
  {
    id: 54,
    name: "Chukka Boots",
    category: "Footwear",
    price: 94.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/chukkaboots/300/300.jpg",
    badge: null,
    rating: 4.4,
    reviews: 22,
    tab: "best",
  },
  {
    id: 55,
    name: "Kids' Summer Dress",
    category: "Kids' Wear",
    price: 24.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/kidsdress/300/300.jpg",
    badge: "New",
    rating: 4.9,
    reviews: 7,
    tab: "new",
  },
  {
    id: 56,
    name: "Harrington Jacket",
    category: "Outerwear",
    price: 84.99,
    oldPrice: 109.99,
    image: "https://picsum.photos/seed/harrington/300/300.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 19,
    tab: "sale",
  },
  {
    id: 57,
    name: "Crewneck Sweatshirt",
    category: "Women's Wear",
    price: 39.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/crewneck/300/300.jpg",
    badge: null,
    rating: 4.3,
    reviews: 52,
    tab: "best",
  },
  {
    id: 58,
    name: "Running Crops",
    category: "Activewear",
    price: 49.99,
    oldPrice: 64.99,
    image: "https://picsum.photos/seed/runningcrops/300/300.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 44,
    tab: "sale",
  },
  {
    id: 59,
    name: "Striped Cotton Socks (3-Pack)",
    category: "Accessories",
    price: 14.99,
    oldPrice: null,
    image: "https://picsum.photos/seed/socks/300/300.jpg",
    badge: null,
    rating: 4.0,
    reviews: 67,
    tab: "best",
  },
  {
    id: 60,
    name: "Trench Coat",
    category: "Outerwear",
    price: 179.99,
    oldPrice: 229.99,
    image: "https://picsum.photos/seed/trenchcoat/300/300.jpg",
    badge: "Sale",
    rating: 4.9,
    reviews: 35,
    tab: "sale",
  },
];
