// func/data.js
export const products = [
  {
    id: 2,
    name: "Camiseta Básica Regular",
    slug: "camiseta-basica-regular",
    category: "casual",
    price: 89.99,
    oldPrice: 119.99,
    image: "assets/img/camiseta_basica_branca.jpg",
    badge: "Sale",
    rating: 4.8,
    reviews: 28,
    tab: "sale",
  },

  {
    id: 6,
    name: "Camiseta Minimalista Vintcy",
    slug: "camiseta-minimalista-vintcy",
    category: "casual",
    price: 129.99,
    oldPrice: 159.99,
    image: "assets/img/camiseta_minimalista_vintcy.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 22,
    tab: "sale",
  },

  {
    id: 9,
    name: "Polo Casual Detalhe Slim",
    slug: "polo-casual-detalhe-slim",
    category: "polos",
    price: 99.99,
    oldPrice: 79.99,
    image: "assets/img/polo_casual_detalhe_slim.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 27,
    tab: "sale",
  },
  {
    id: 10,
    name: "Polo Essencial de Malha",
    slug: "polo-essencial-de-malha",
    category: "polos",
    price: 79.99,
    oldPrice: null,
    image: "assets/img/polo_essencial_de_malha.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 15,
    tab: "new",
  },
  {
    id: 12,
    name: "Terno Alfaiate Completo",
    slug: "terno-alfaiate-completo",
    category: "social",
    price: 469.99,
    oldPrice: null,
    image: "assets/img/terno_alfaiate_completo.jpg",
    badge: null,
    rating: 4.3,
    reviews: 41,
    tab: "best",
  },
  {
    id: 15,
    name: "Calça de Alfaiataria Slim Fit",
    slug: "calca-de-alfaiataria-slim-fit",
    category: "calças",
    price: 144.99,
    oldPrice: null,
    image: "assets/img/Calça_de_Alfaiataria_Slim_Fit.jpg",
    badge: null,
    rating: 4.2,
    reviews: 24,
    tab: "best",
  },

  {
    id: 18,
    name: "Camisa Slim fit",
    slug: "camisa-slim-fit",
    category: "social",
    price: 69.99,
    oldPrice: null,
    image: "assets/img/Camisa_Slim_fit.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 13,
    tab: "new",
  },
  {
    id: 20,
    name: "Jaqueta Casual de Sarja",
    slug: "jaqueta-casual-de-sarja",
    category: "jaquetas",
    price: 264.99,
    oldPrice: 79.99,
    image: "assets/img/Jaqueta_Casual_de_Sarja.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 29,
    tab: "sale",
  },
  {
    id: 21,
    name: "Jaqueta Corta-Vento Casual",
    slug: "jaqueta-corta-vento-casual",
    category: "jaquetas",
    price: 254.99,
    oldPrice: 74.99,
    image: "assets/img/Jaqueta_Corta-Vento_Casual.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 61,
    tab: "sale",
  },
  {
    id: 24,
    name: "Moletom Careca Básico",
    slug: "moletom-careca-basico",
    category: "moletons",
    price: 149.99,
    oldPrice: 199.99,
    image: "assets/img/Moletom_Careca_Básico.jpg",
    badge: "Sale",
    rating: 4.6,
    reviews: 38,
    tab: "sale",
  },
  {
    id: 25,
    name: "Moletom com Zíper e Capuz",
    slug: "moletom-com-ziper-e-capuz",
    category: "moletons",
    price: 294.99,
    oldPrice: null,
    image: "assets/img/Moletom_com_Zíper_e_Capuz.jpg",
    badge: null,
    rating: 4.8,
    reviews: 44,
    tab: "best",
  },
  {
    id: 26,
    name: "Calça Jeans Reta",
    slug: "calca-jeans-reta",
    category: "calças",
    price: 234.99,
    oldPrice: 44.99,
    image: "assets/img/Calça_Jeans_Reta.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 51,
    tab: "sale",
  },

  {
    id: 33,
    name: "Cinto Social de Couro Texturizado",
    slug: "cinto-social-de-couro-texturizado",
    category: "acessorios",
    price: 57.99,
    oldPrice: null,
    image: "assets/img/Cinto_Social_de_Couro_Texturizado.jpg",
    badge: "New",
    rating: 4.8,
    reviews: 9,
    tab: "new",
  },
  {
    id: 35,
    name: "Gravata Social com Padrão Listrado",
    slug: "gravata-social-com-padrao-listrado",
    category: "acessorios",
    price: 59.99,
    oldPrice: 129.99,
    image: "assets/img/Gravata_Social_com_Padrão_Listrado.jpg",
    badge: "Sale",
    rating: 4.7,
    reviews: 55,
    tab: "sale",
  },

  {
    id: 37,
    name: "Meias Sociais Clássicas",
    slug: "meias-sociais-classicas",
    category: "acessorios",
    price: 27.9,
    oldPrice: 49.99,
    image: "assets/img/Meias_Sociais_Clássicas.jpg",
    badge: "Sale",
    rating: 4.5,
    reviews: 71,
    tab: "sale",
  },
  {
    id: 39,
    name: "Relógio Casual Cronógrafo",
    slug: "relogio-casual-cronografo",
    category: "acessorios",
    price: 459.99,
    oldPrice: null,
    image: "assets/img/Relógio_Casual_Cronógrafo.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },

  {
    id: 40,
    name: "Bermuda Cargo",
    slug: "bermuda-cargo",
    category: "bermudas",
    price: 129.99,
    oldPrice: null,
    image: "assets/img/Bermuda_Cargo.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 41,
    name: "Bermuda Chino",
    slug: "bermuda-chino",
    category: "bermudas",
    price: 129.99,
    oldPrice: null,
    image: "assets/img/Bermuda_Chino.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 42,
    name: "Bota Brogue",
    slug: "bota-brogue",
    category: "botas",
    price: 259.99,
    oldPrice: null,
    image: "assets/img/Bota_Brogue.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 43,
    name: "Bota Chelsea",
    slug: "bota-chelsea",
    category: "botas",
    price: 359.99,
    oldPrice: null,
    image: "assets/img/Bota_Chelsea.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 44,
    name: "Mocassim Driver de Camurça",
    slug: "mocassim-driver-de-camurca",
    category: "mocassins",
    price: 259.99,
    oldPrice: null,
    image: "assets/img/Mocassim_Driver_de_Camurça.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 45,
    name: "Mocassim Penny de Couro ",
    slug: "mocassim-penny-de-couro",
    category: "mocassins",
    price: 259.99,
    oldPrice: null,
    image: "assets/img/Mocassim_Penny_de_Couro_Marrom.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 46,
    name: "Tênis Casual de Couro Liso ",
    slug: "tenis-casual-de-couro-liso",
    category: "tenis",
    price: 159.99,
    oldPrice: null,
    image: "assets/img/Tênis_Casual_de_Couro_Liso.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 47,
    name: "Tênis de Couro com Detalhes de Camurça",
    slug: "tenis-de-couro-com-detalhes-de-camurca",
    category: "tenis",
    price: 259.99,
    oldPrice: null,
    image: "assets/img/Tênis_de_Couro_com_Detalhes_de_Camurça.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 48,
    name: "Sapato Monk Strap Duplo",
    slug: "sapato-monk-strap-duplo",
    category: "sapatos",
    price: 259.99,
    oldPrice: null,
    image: "assets/img/Sapato_Monk_Strap_Duplo_Preto.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 49,
    name: "Sapato Oxford Cap-Toe",
    slug: "sapato-oxford-cap-toe",
    category: "sapatos",
    price: 259.99,
    oldPrice: null,
    image: "assets/img/Sapato_Oxford_Cap-Toe.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 50,
    name: "Mochila de Couro Minimalista",
    slug: "mochila-de-couro-minimalista",
    category: "mochilas",
    price: 159.99,
    oldPrice: null,
    image: "assets/img/Mochila_de_Couro_Minimalista.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
  {
    id: 51,
    name: "Mochila de Couro Roll-Top",
    slug: "mochila-de-couro-roll-top",
    category: "mochilas",
    price: 159.99,
    oldPrice: null,
    image: "assets/img/Mochila_de_Couro_Roll-Top.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 16,
    tab: "new",
  },
];

export function getProductById(id) {
  return products.find((p) => Number(p.id) === Number(id)) || null;
}

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === String(slug)) || null;
}
